<a href="https://colab.research.google.com/github/Julia-A-Casillas/everpeak-analysis/blob/main/Sprint_5_FOCUS_Practica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({
    "nombre": ["Ana", "Luis", "María", "Sara", "Julián", "Camila"],
    "edad": [23, 35, 29, 41, 33, 25],
    "ciudad": ["Bogotá", "Medellín", "Cali", "Cali", "Bogotá", "Medellín"],
    "ingresos": [2500, 3200, 2800, 4500, 3900, 3100],
    "plan": ["Free", "Pro", "Free", "Enterprise", "Pro", "Free"]
})

In [ ]:
df

   nombre  edad    ciudad  ingresos        plan
0     Ana    23    Bogotá      2500        Free
1    Luis    35  Medellín      3200         Pro
2   María    29      Cali      2800        Free
3    Sara    41      Cali      4500  Enterprise
4  Julián    33    Bogotá      3900         Pro
5  Camila    25  Medellín      3100        Free

In [ ]:
df['ciudad']

0      Bogotá
1    Medellín
2        Cali
3        Cali
4      Bogotá
5    Medellín
Name: ciudad, dtype: object

In [ ]:
df[['ciudad','ingresos']]

     ciudad  ingresos
0    Bogotá      2500
1  Medellín      3200
2      Cali      2800
3      Cali      4500
4    Bogotá      3900
5  Medellín      3100

In [ ]:
df[['ciudad','ingresos','edad']]

     ciudad  ingresos  edad
0    Bogotá      2500    23
1  Medellín      3200    35
2      Cali      2800    29
3      Cali      4500    41
4    Bogotá      3900    33
5  Medellín      3100    25

In [ ]:
df['ingresos'] >= 3200

0    False
1     True
2    False
3     True
4     True
5    False
Name: ingresos, dtype: bool

In [ ]:
df[df['ingresos'] >= 3200]

   nombre  edad    ciudad  ingresos        plan
1    Luis    35  Medellín      3200         Pro
3    Sara    41      Cali      4500  Enterprise
4  Julián    33    Bogotá      3900         Pro

In [ ]:
df[(df['ingresos'] >= 3200) & (df['plan'] == 'Pro')]

   nombre  edad    ciudad  ingresos plan
1    Luis    35  Medellín      3200  Pro
4  Julián    33    Bogotá      3900  Pro

In [ ]:
df[(df['ingresos'] >= 3200) | (df['plan'] == 'Pro')]

   nombre  edad    ciudad  ingresos        plan
1    Luis    35  Medellín      3200         Pro
3    Sara    41      Cali      4500  Enterprise
4  Julián    33    Bogotá      3900         Pro

In [ ]:
df

   nombre  edad    ciudad  ingresos        plan
0     Ana    23    Bogotá      2500        Free
1    Luis    35  Medellín      3200         Pro
2   María    29      Cali      2800        Free
3    Sara    41      Cali      4500  Enterprise
4  Julián    33    Bogotá      3900         Pro
5  Camila    25  Medellín      3100        Free

In [ ]:
df.groupby('ciudad')['ingresos'].sum() #suma

ciudad
Bogotá      6400
Cali        7300
Medellín    6300
Name: ingresos, dtype: int64

In [ ]:
df.groupby('ciudad')['ingresos'].mean() #promedio

ciudad
Bogotá      3200.0
Cali        3650.0
Medellín    3150.0
Name: ingresos, dtype: float64

In [ ]:
df.groupby('ciudad')['ingresos'].agg(['sum','mean','min','max']) #ejecuta varias operaciones dentro del agg

           sum    mean   min   max
ciudad
Bogotá    6400  3200.0  2500  3900
Cali      7300  3650.0  2800  4500
Medellín  6300  3150.0  3100  3200

Union de dos DataFrames

Dataframe es una tabla

In [ ]:
df1 = pd.DataFrame({'ID': [1, 2, 3],
                    'Nombre': ['Ana', 'Benito', 'Carla']})
df2 = pd.DataFrame({'ID': [4, 5, 6],
                    'Nombre': ['Sofia', 'Mateo', 'Jose']})

In [ ]:
df2.rename(columns={'Nompre_persona': 'Nombre'}, inplace=True)

In [ ]:
pd.concat([df1,df2,df1])

   ID  Nombre
0   1     Ana
1   2  Benito
2   3   Carla
0   4   Sofia
1   5   Mateo
2   6    Jose
0   1     Ana
1   2  Benito
2   3   Carla

In [ ]:
df_completo = pd.concat([df1, df2])

In [ ]:
df_completo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      6 non-null      int64
 1   Nombre  6 non-null      object
dtypes: int64(1), object(1)
memory usage: 144.0+ bytes

In [ ]:
df_completo = pd.concat([df1, df2, df1, df2])

JOINS

In [ ]:
clientes = pd.DataFrame({
    "id": [1, 2, 3, 4, 5],
    "nombre": ["Ana", "Luis", "María", "Carlos", "Sofía"]
})
clientes

   id  nombre
0   1     Ana
1   2    Luis
2   3   María
3   4  Carlos
4   5   Sofía

In [ ]:
compras = pd.DataFrame({
    "id_cliente": [1, 2, 2, 4, 6],
    "producto": ["Laptop", "Mouse", "Teclado", "Monitor", "Tablet"]
})
compras

   id_cliente producto
0           1   Laptop
1           2    Mouse
2           2  Teclado
3           4  Monitor
4           6   Tablet

In [ ]:
clientes.merge(compras,how='inner', on='id_cliente')

   id_cliente  nombre producto
0           1     Ana   Laptop
1           2    Luis    Mouse
2           2    Luis  Teclado
3           4  Carlos  Monitor

In [ ]:
clientes.merge(compras,how='inner', left_on='id', right_on='id_cliente')

   id  nombre  id_cliente producto
0   1     Ana           1   Laptop
1   2    Luis           2    Mouse
2   2    Luis           2  Teclado
3   4  Carlos           4  Monitor

In [ ]:
clientes.merge(compras,how='left', left_on='id', right_on='id_cliente')

   id  nombre  id_cliente producto
0   1     Ana         1.0   Laptop
1   2    Luis         2.0    Mouse
2   2    Luis         2.0  Teclado
3   3   María         NaN      NaN
4   4  Carlos         4.0  Monitor
5   5   Sofía         NaN      NaN

In [ ]:
clientes.merge(compras,how='right', left_on='id', right_on='id_cliente')

    id  nombre  id_cliente producto
0  1.0     Ana           1   Laptop
1  2.0    Luis           2    Mouse
2  2.0    Luis           2  Teclado
3  4.0  Carlos           4  Monitor
4  NaN     NaN           6   Tablet

In [ ]:
clientes.merge(compras,how='outer', left_on='id', right_on='id_cliente')

    id  nombre  id_cliente producto
0  1.0     Ana         1.0   Laptop
1  2.0    Luis         2.0    Mouse
2  2.0    Luis         2.0  Teclado
3  3.0   María         NaN      NaN
4  4.0  Carlos         4.0  Monitor
5  5.0   Sofía         NaN      NaN
6  NaN     NaN         6.0   Tablet

In [ ]:
# Nuevo análisis: detectar outliers con IQR - Sprint 7
Q1 = df['order_value'].quantile(0.25)
Q3 = df['order_value'].quantile(0.75)
IQR = Q3 - Q1
upper = Q3 + 1.5*IQR
df['outlier_flag'] = df['order_value'] > upper

NameError: name 'df' is not defined